### ISSUE TITLE
Sticker

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MetaboCoreUtils#19]
We need obviously also a sticker for this one. Happy to collect ideas etc.

**Comment by michaelwitting** [comment]
A cool metabolite structure should be in there... something with a ring. One of my favorite metabolites is Tryptophan

**Comment by jorainer** [comment]
How about this sticker?

![MetaboCoreUtils](https://user-images.githubusercontent.com/5506112/102890160-462d8380-445c-11eb-8cc7-ac96071c3d20.png)

- it contains also Tryptophan :)

**Comment by michaelwitting** [comment]
Good to me!
