### ISSUE TITLE
List of commerical internal standard mixtures

### ISSUE THREAD

**Issue by michaelwitting** [rformassspectrometry/MetaboCoreUtils#28]
Hi,

I'm using several metabolite and lipid mixtures with isotopically labeled standards for QC etc. What do you think about having them in `MetaboCoreUtils` with the names, formula, exact mass, concentration and a function calling the specific product. The data could be in a file that is read and then a function like `getIsMix(mix = "QReSS")` returns a `data.frame` with the metabolites contained.

Best,

Michael

**Comment by michaelwitting** [comment]
One examples is the QReSS Mix from CIL:

https://www.isotope.com/userfiles/files/assetLibrary/MET_RSCH_QReSS.pdf

**Comment by jorainer** [comment]
That sounds like a good idea. But I would call the function rather `internalStandards(mix = "QReSS")` instead.

**Comment by michaelwitting** [comment]
Great! I will prototype some tables and a function soonish!

**Comment by michaelwitting** [comment]
@jorainer: Some input would be nice. In several mixes the substances are present as sodium salt, so to correctly calculate the concentration we need to incorporate that. We should have fields with the structure from the salt and the free metabolite so both can be used. I'm suggesting following fields:

- `name`
- `formula.salt` or `formulaSalt`
- `formula.metabolite` or `formulaMetabolite`
-  `smiles.salt` or `smilesSalt`
- `smiles.metabolites` or `smilesMetabolite`
- `molweight.salt` or `molweightSalt` (required for conversion of concentration from µg/mL to something molar)
- `exactmass.metabolite` or `exactMassMetabolite` (required for m/z calculation)

Maybe @stanstrup or @sneumann have some opinion on this?

**Comment by jorainer** [comment]
I'm fine with that - and I would suggest the `camelCase` option.

**Comment by michaelwitting** [comment]
Good... will be the `camelCase`

**Comment by jorainer** [comment]
I think we can close this issue now - feel free to re-open if needed.

**Comment by michaelwitting** [comment]
I will add more standard mixes, once I find some time.
