### ISSUE TITLE
mass2mz and mz2mass to support multiple adducts

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MetaboCoreUtils#29]
Currently `mass2mz` and `mz2mass` allow only to convert mass to m/z or *vice-versa* for a **single** adduct. Would be nice to support calls such as e.g.

```r
mass2mz(c(312.43, 431.21, 322.21), adducts = c("[M+H]+", "[M+Na]+"))
```

and I would suggest that this call would return a `matrix` with 3 rows (one row per mass) and 2 columns (one column per adduct). That should be pretty efficient to calculate and it would also support extracting then just e.g. one adduct etc.

@michaelwitting any thoughts?

**Comment by michaelwitting** [comment]
Agreed! Great idea.
