### ISSUE TITLE
Retention time indexing for metabolomics

### ISSUE THREAD

**Issue by michaelwitting** [rformassspectrometry/MetaboCoreUtils#33]
Hi,

some time ago I was working on some code to convert retention times into retention indices. Would this fit to MetaboCoreUtils?
With this it might be interesting to work on this: https://github.com/rformassspectrometry/MetaboCoreUtils/issues/20

Best,

Michael

**Comment by jorainer** [comment]
hmm - if it works on base R objects, sure.

**Comment by michaelwitting** [comment]
This idea is to have an input `matrix` with `mz` and `rtime` column as minimum and another `matrix` containing expected `mz`, `rtime` and `rindex` for the retention index marker. Then the function searches for the markers and their real values and uses them to transform `rtime` to `rindex`. Output would be a `matrix` with `mz`, `rtime`, `rindex`.
Or do you prefer a `data.frame`?
