### ISSUE TITLE
Create a formula2mz function

### ISSUE THREAD

**Issue by RogerGinBer** [rformassspectrometry/MetaboCoreUtils#55]
As discussed in https://github.com/rformassspectrometry/CompoundDb/issues/99, it'd be nice to have a `formula2mz` function that, given a list of molecular formulas and a list of adducts, calculates a matrix of the corresponding mz's using `calculateMass` and `mass2mz`

**Comment by jorainer** [comment]
If you would like to contribute that function, feel free to do so (and assign yourself the issue).
