### ISSUE TITLE
add possibility to use deuterium to "calculateMass()"

### ISSUE THREAD

**Issue by mar-garcia** [rformassspectrometry/MetaboCoreUtils#81]
Is it possible to include a "deuterated" element when calculating the exact mass of a formula? Using "D" is not possible... Not sure if it is not possible or maybe I'm using the wrong symbol.... 
In the former case, maybe could be nice to be able to use also deteurium as an element defining the chemical formula when using calculateMass()....
For example, with "D" it is working if I use the `Rdisop::getMolecule()` function....

**Comment by sgibb** [comment]
Could you please provide an example formular with an expected mass?

Deuterium is currently supported using `calculateMass("[2H]")`.

**Comment by mar-garcia** [comment]
Sure! Let's take [tryptophan-d5](https://pubchem.ncbi.nlm.nih.gov/substance/24881953) as example, with Rdisop package I would calculate the exact mass in this way `Rdisop::getMolecule("C11D5H7N2O2")$exactmass`

**Comment by sgibb** [comment]
You have to add `[2Hx]`, e.g.:

```r
Rdisop::getMolecule("C11D5H7N2O2")$exactmass
# [1] 209.1213

MetaboCoreUtils::calculateMass("C11[2H5]H7N2O2")
# C11[2H5]H7N2O2 
#       209.1213 
```

Please feel free to reopen if this solution doesn't fit.

**Comment by mar-garcia** [comment]
Sure! Good idea @jorainer! :)
Thanks!
